---
name: Calendar
version: 0.0.1
main: JonasWindmann\Calendar\Main
api: 5.32.1
src-namespace-prefix: JonasWindmann\Calendar
depend:
  - CoreAPI
permissions:
  calendar.command:
    default: true
  calendar.edit:
    default: op
...
